name: Android UI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: self-hosted
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Android SDK PATH
        run: |
          echo "$HOME/Android/platform-tools" >> "$GITHUB_PATH"
          echo "$HOME/Android/emulator" >> "$GITHUB_PATH"
          echo "$HOME/Android/cmdline-tools/latest/bin" >> "$GITHUB_PATH"

      - name: Restart headless emulator (systemd --user)
        run: |
          systemctl --user daemon-reload || true
          systemctl --user restart android-emulator.service
          sleep 2
          systemctl --user --no-pager status android-emulator.service || true

      - name: Wait for boot with heartbeat
        run: bash android-hello/scripts/wait-boot.sh

      - name: Build & Install Debug
        working-directory: demo-app
        run: ./gradlew --no-daemon :app:assembleDebug :app:installDebug

      - name: Connected UI Tests
        working-directory: demo-app
        run: ./gradlew --no-daemon :app:connectedDebugAndroidTest

      - name: Collect artifacts (logs & reports)
        if: always()
        run: |
          mkdir -p artifacts
          adb -s emulator-5554 exec-out screencap -p > artifacts/screenshot.png || true
          adb -s emulator-5554 logcat -d > artifacts/logcat.txt || true
          journalctl --user -u android-emulator.service -e -n 1000 > artifacts/emulator.log || true
          cp ~/.config/systemd/user/android-emulator.service artifacts/emulator.service || true
          # レポート類を拾う
          if [ -d demo-app/app/build/reports/androidTests/connected ]; then
            cp -r demo-app/app/build/reports/androidTests/connected artifacts/test-report || true
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-ui-artifacts
          path: |
            artifacts
